# <font color =indianred >**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch
import time

# <font color = indianred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [3]:
my_tensor = torch.zeros((5,3))

In [4]:
my_tensor.shape

torch.Size([5, 3])

In [5]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".
my_tensor[0,2]=10
my_tensor[2,0]=100
# CODE HERE

In [7]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = indianred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [8]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [9]:
x = x.reshape(6,4).t()
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = indianred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [10]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [11]:
x.shape

torch.Size([3, 5])

In [12]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desiindianred row.
last_row = x[-1:,:]
last_row

tensor([[11, 12, 13, 14, 15]])

In [13]:
# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:,3]
fourth_column

tensor([ 4,  8, 14])

In [14]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the requiindianred subset of rows and columns.
first_3_rows_2_columns = x[:3,:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [15]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the requiindianred subset of rows and columns with odd indices.
odd_valued_rows_columns = x[::2,::2]
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = indianred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [16]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [17]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [18]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [19]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [20]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [21]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = x.mean(axis=0)

  # Calculate the standard deviation along each column
  std = x.std(axis=0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x-mean)/std

  return y  # Return the normalized matrix



In [22]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [23]:
Z.mean(axis = 0) # mean is close to 0

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

In [24]:
Z.std(axis=0) # std is close to 1

tensor([1., 1., 1., 1.])

# <font color = 'indianred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [25]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', A.data_ptr())
A.add_(5)
print('Memory address of A after in-place addition:',  A.data_ptr())
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', B.data_ptr())
B=B+5
print('Memory address of B after out-of-place addition:',B.data_ptr())
print('B after out-of-place addition:', B)


Original memory address of A: 626786752
Memory address of A after in-place addition: 626786752
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 553317760
Memory address of B after out-of-place addition: 626782464
B after out-of-place addition: tensor([ 9, 10, 11])


**Provide Explanation for above question here :**
- in-place operations like .add_(),.mul_(), etc save memory but can overwrite values, the memory address remains the same before and after the operation
- out-of-place operations +, .add() they are allocated new tensors in memory and do not alter the original tensor. this is a safer for operations but in place is more memory efficient


# <font color = 'indianred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [26]:
X = torch.tensor([[1],[2],[3]])
Y = torch.tensor([[4,5,6]])
print('Original shapes:', X.shape, Y.shape)
result = X+Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**
- Broadcasting is the process that allows operations (like addition, multiplication) on tensors of different shapes without explicitly replicating data
- based on the above examples it X columns  is expanded to shape (3X3) and Y is expanded row wise to shape (3X3). Follwing this expansion, element-wise addition is carried out



# <font color = 'indianred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [27]:
M1 = torch.tensor([[1,2],[3,4]])
M2 = torch.tensor([[5,6],[7,8]])
mat_multiplication =  M1*M2
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.tensor([1,2,3])
V2 =  torch.tensor([2,3,4])
dot_product = torch.dot(V1,V2)
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[ 5, 12],
        [21, 32]])
Dot product: tensor(20)


# <font color = 'indianred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [29]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3,8)
print('T_view shape:', T_view.shape)

T_reshape = T.reshape(4,2,3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2,1,0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**
- view vs reshape: view only works when the tensor is stored in a contiguous block of memory and creates a new voew of the same data without copying
- reshape is more flexible - it will return a view if possible, but if not it creates a copy of the data with the new shape
- permute: reorders dimensions by chainging strides only (no data movement)
in this case the first and last was swapped



# <font color = 'indianred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [30]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 = torch.cat((C1,C2),dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat((C1,C2),dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack((C1,C2),dim=0)
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**
- concatenation: joins tensors along an existing dimension, the number of dimenstion dont change, from the above examples shape (2,3) along dim=0 produces a (4,3) tensor by adding rows, while concatenating along dim=1 produces a (2,6) tensor by adding columns.

- stacking: creates a new dimension and puts the input tensors along it, the number of dumenstions increses by 1. All the tensors must have the same shape



# <font color = 'indianred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [39]:
D = torch.rand(6, 6)
print(D)
print('Elements greater than 0.5:\n',  D[D>0.5])

second_fourth_rows =  D[[1,3],:]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 = D[:3,:3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)


tensor([[0.7825, 0.0062, 0.6790, 0.2412, 0.3765, 0.8734],
        [0.0292, 0.7236, 0.7633, 0.3242, 0.4825, 0.9024],
        [0.9684, 0.2931, 0.8377, 0.0136, 0.2148, 0.4112],
        [0.4864, 0.6531, 0.8119, 0.7262, 0.5340, 0.5329],
        [0.2394, 0.6133, 0.7810, 0.9976, 0.1765, 0.5893],
        [0.0147, 0.3923, 0.4603, 0.7624, 0.7665, 0.0825]])
Elements greater than 0.5:
 tensor([0.7825, 0.6790, 0.8734, 0.7236, 0.7633, 0.9024, 0.9684, 0.8377, 0.6531,
        0.8119, 0.7262, 0.5340, 0.5329, 0.6133, 0.7810, 0.9976, 0.5893, 0.7624,
        0.7665])

Second and fourth rows:
 tensor([[0.0292, 0.7236, 0.7633, 0.3242, 0.4825, 0.9024],
        [0.4864, 0.6531, 0.8119, 0.7262, 0.5340, 0.5329]])

Top-left 3x3 block:
  tensor([[0.7825, 0.0062, 0.6790],
        [0.0292, 0.7236, 0.7633],
        [0.9684, 0.2931, 0.8377]])


# <font color = 'indianred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [46]:
import math
G = torch.arange(0,math.pi+0.0001, math.pi/4)
print('G:', G)
print('Sine of G:',  torch.sin(G))
print('Cosine of G:',  torch.cos(G))
print('Tangent of G:', torch.tan(G))
print('Natural logarithm of G:',  torch.log(G))
print('Exponential of G:', torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
Sine of G: tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01, -1.0000e+00])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00,  8.7423e-08])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570,  1.1447])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507, 23.1407])


# <font color = 'indianred'>Q12: **Tensor reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [52]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  torch.sum(H))
print('Shape after Sum of H:',  torch.sum(H).shape,  end = "\n\n")

print('Sum of H along dimension 0:', torch.sum(H,dim=0))
print('Shape after sum of H along dimension 0:',  torch.sum(H,dim=0).shape,  end = "\n\n")

print('Sum of H along dimension 1:', torch.sum(H,dim=1))
print('Shape after sum of H along dimension 1:',  torch.sum(H,dim=1).shape)


H: tensor([[0.3021, 0.9761],
        [0.5550, 0.4309],
        [0.2430, 0.5745]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(3.0816)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([1.1001, 1.9815])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([1.2782, 0.9859, 0.8175])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**
- torch.sum(H) :- reduced all dimensions and return a scaler torch.Size([])
- torch.sum(H,dim=0):- it adds all the values in the columns
- torch.sum(H,dim=1):- adds all the values in the rows


# <font color = 'indianred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [53]:
# Solution for Q16
I =  torch.tensor([1,2,3],dtype=torch.float32)
print('I:', I)
I_int =  I.to(torch.int32)
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**
- Tensor data types determine both precision and memory usage
floating-point types () are essential for mathematical operations such as divion, trignometric functions and gradient computations in deep learning.
- integer types are more appropriate for tasks like categorical indices, counters or labels
- when converting between data types, converting floats to integers truncates decimal values, which may lead to information loss
- using lower-precision floats like float16 can reduce memory consumption but risks rounding errors


# <font color = 'indianred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [58]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024,1024)
B = torch.randn(1024,1024)

In [55]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.04089665412902832 seconds


In [56]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(B.shape[1]):
  C[:,i]=torch.mv(A,B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 1.4014976024627686 seconds


In [59]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    C[i,j]=torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 18.01245355606079 seconds


# <font color = 'indianred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'indianred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [3]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [4]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [5]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.20945501327514648 seconds


In [6]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(B.shape[1]):
  C[:,i]=torch.mv(A,B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.14329242706298828 seconds


In [7]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    C[i,j]=torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 45.72378897666931 seconds
