# Back Propogation

In [1]:
import torch 

In [6]:
x=torch.tensor(4.0,requires_grad=True)
x 

tensor(4., requires_grad=True)

In [7]:
y=x**2 
y

tensor(16., grad_fn=<PowBackward0>)

In [12]:
## back propagation 
# y=2x 
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [10]:
print(x.grad) 

tensor(8.)


In [11]:
x 

tensor(4., requires_grad=True)

In [15]:
# nested list 
lst=[[2,3,1],[4,5,3],[7,6,4]]
torch_input=torch.tensor(lst,dtype=torch.float32,requires_grad=True)
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [ ]:
#y=x**3+x**2
#dy/dx=3*x**2 + 2*x
y=torch_input**3+torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [18]:
z=y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [19]:
z.backward()

In [20]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])