In [2]:
import torch 
import numpy as np 


In [3]:
lst=[3,4,5,6]
arr=np.array(lst)
arr.dtype

dtype('int32')

# convert numpy to pytorch tensors

In [4]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [5]:
# indexing similar to numpy 
print(tensors[:2])
tensors[2]=10
tensors,arr 

tensor([3, 4], dtype=torch.int32)


(tensor([ 3,  4, 10,  6], dtype=torch.int32), array([ 3,  4, 10,  6]))

In [6]:
# copy of the array torch.tensor()
tensors2=torch.tensor(arr)
tensors2[2]=12
tensors2,arr 

(tensor([ 3,  4, 12,  6], dtype=torch.int32), array([ 3,  4, 10,  6]))

# in built functions in pytorch

In [7]:
# zeros 
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [8]:
torch.ones(3,4,dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

# Arithmetic operations

In [9]:
a=torch.tensor([3,4,5],dtype=torch.float32)
b=torch.tensor([5,6,7],dtype=torch.float64)
print(a+b)

tensor([ 8., 10., 12.], dtype=torch.float64)


In [10]:
c=torch.zeros(3)
c=torch.add(a,b,out=c)
print(c)

tensor([ 8., 10., 12.])


In [11]:
torch.add(a,b,out=c).sum() 

tensor(30.)

In [12]:
a=torch.tensor(np.arange(0,15).reshape(5,3))
b=torch.tensor(np.arange(15,30).reshape(5,3))

In [13]:
c=a+b 
c.sum()

tensor(435)

In [14]:
c[3,[0,2]]

tensor([33, 37], dtype=torch.int32)

# dot product and multi operation

In [15]:
x=torch.tensor([3,4,5,6],dtype=torch.float32)
y=torch.tensor([7,8,9,10],dtype=torch.float32)
x.mul(y)

tensor([21., 32., 45., 60.])

In [16]:
#3*7+4*8+5*9+6*10
x.dot(y)

tensor(158.)

In [17]:
# matrix multiplocation 
x=torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float64)
y=torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float64)

In [18]:
x.matmul(y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [19]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [20]:
x@y 

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

# to device

In [23]:
# check if gpu is available 
torch.cuda.is_available()

True

In [24]:
device=torch.device("cuda:0"  if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [30]:
x=torch.tensor([1,2,3,4])
x.device

device(type='cpu')

In [31]:
# move tensors to GPU 
x=x.to(device=0)
x.device

device(type='cuda', index=0)

In [32]:
y=torch.tensor([1,2,3,4],device=device)
y.device

device(type='cuda', index=0)

# in place memory operation GPU

In [44]:
t1=torch.randn(10000,10000,device="cpu")

# move tensor to gpu 
t1=t1.to(device)
print(t1.device)

# id() function to get memory address of tensor
print(f"initial memory location of t1 {id(t1)}")
x=t1 
print(f"initial memory location of x {id(x)}")

torch.cuda.synchronize()

# initial memory allocated
start_memory=torch.cuda.memory_allocated()

# inplace operation 
t1+=0.1 
t1.add_(0.1)

# inplace operation therefore the same 
print(x==t1)

print(f"final memory location of tensor t1 is :{id(t1)}")
print(f"final memory location of tensor x is :{id(x)}")

# total memory allocated after function call 
end_memory=torch.cuda.memory_allocated()

# memory allocated because of function call 
memory_allocated=end_memory=start_memory 
print(memory_allocated/1024**2)

cuda:0
initial memory location of t1 2800186939088
initial memory location of x 2800186939088
tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]], device='cuda:0')
final memory location of tensor t1 is :2800186939088
final memory location of tensor x is :2800186939088
382.00048828125


# memory out of place operation

In [46]:
# create tensor
t2 = torch.randn(10000, 10000, device="cpu")

# move tensor to gpu
t2 = t2.to(device)
print(t2.device)

# we can use id() function to get memory location of tensor
print(f"initial memory location of tensor t2 {id(t2)}")

y = t2
print(f"final memory location of y is : {id(y)}")

# Waits for everything to finish running
torch.cuda.synchronize()

# initial memory allocated
start_memory = torch.cuda.memory_allocated()

# out-place opertaions
t2 = t2 + 0.1

# since the operation was not inplace when we update t2 it will not update y
print(y == t2)

# we can use id() function to get memory location of tensor
print(f"final memory location of tensor t2 {id(t2)}")
print(f"final memory location of y is : {id(y)}")

# totall memory allocated after function call
end_memory = torch.cuda.memory_allocated()

# memory allocated because of function call
memory_allocated = end_memory - start_memory
print(memory_allocated / 1024**2)

cuda:0
initial memory location of tensor t2 2800230228992
final memory location of y is : 2800230228992
tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]], device='cuda:0')
final memory location of tensor t2 2800249332336
final memory location of y is : 2800230228992
382.0
