In [1]:
import torch
import torch.nn as nn 
from torch.utils import data 
import torch.nn.functional as F 
import random 
import math 
from torchviz import make_dot

In [2]:
class LinearRegression(nn.Module):
    """ 
    A linear regression model that predicts a real-valued outputs
    """
    def __init__(self, input_dim,output_dim):
        super().__init__()
        self.inplut_dim=input_dim
        self.output_dim=output_dim 
        self.weights=nn.Parameter(torch.randn(self.output_dim,self.inplut_dim)/math.sqrt(self.inplut_dim))
        self.biases=nn.Parameter(torch.zeros(1))

    def forward(self,x):
        return x @ self.weights.T + self.biases  

In [9]:
x=torch.arange(6).view(3,2).float()
input_dim=2
output_dim=1 
model=LinearRegression(input_dim,output_dim)
output=model(x) # calling the forward function 
output

tensor([[ 0.2896],
        [-0.0928],
        [-0.4752]], grad_fn=<AddBackward0>)

In [10]:
print(f"input shape {x.shape}")
print(f'output shape {output.shape}')

input shape torch.Size([3, 2])
output shape torch.Size([3, 1])


In [16]:
model.weights, model.biases

(Parameter containing:
 tensor([[-0.4808,  0.2896]], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True))

In [ ]:
# gives learnable parameters - updates using gradient descent
list(model.parameters())

[Parameter containing:
 tensor([[-0.4808,  0.2896]], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True)]

In [ ]:
# gives all the parameters 
model.state_dict()

OrderedDict([('weights', tensor([[-0.4808,  0.2896]])),
             ('biases', tensor([0.]))])

# Linear module

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self,input_dim,output_dim):
        super().__init__()
        self.input_dim=input_dim
        self.output_dim=output_dim
        self.linear_layer=nn.Linear(input_dim,output_dim)
        # no weights or bias values - 

    def forward(self,x):
        return self.linear_layer(x)

In [20]:
x=torch.arange(6).view(3,2).float()
model=LinearRegression(2,1)
output=model(x)
mdoel=nn.Linear(2,1)
output2=model(x)

In [21]:
output, output2

(tensor([[0.4345],
         [2.3237],
         [4.2130]], grad_fn=<AddmmBackward0>),
 tensor([[0.4345],
         [2.3237],
         [4.2130]], grad_fn=<AddmmBackward0>))

In [23]:
# method 1
def mse_loss(ypred,y):
    error=ypred-y
    mean_square_error=torch.mean(error**2)
    return mean_square_error
# method 2 
loss_nn=nn.MSELoss(reduction='mean')
# method 3
loss_function=F.mse_loss 

x=torch.tensor([0,1,2,3,4],dtype=torch.float32)
y=torch.tensor([1,3,5,7,9],dtype=torch.float32)

ypred=2*x

loss_manual=mse_loss(ypred,y)
loss_nn_module=loss_nn(y,ypred)
loss_function=loss_function(y,ypred)
print(loss_manual,loss_nn_module,loss_function)


tensor(1.) tensor(1.) tensor(1.)
