In [3]:
import torch 
import numpy as np 


In [4]:
lst=[3,4,5,6]
arr=np.array(lst)
arr.dtype

dtype('int32')

# convert numpy to pytorch tensors

In [5]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [6]:
# indexing similar to numpy 
print(tensors[:2])
tensors[2]=10
tensors,arr 

tensor([3, 4], dtype=torch.int32)


(tensor([ 3,  4, 10,  6], dtype=torch.int32), array([ 3,  4, 10,  6]))

In [7]:
# copy of the array torch.tensor()
tensors2=torch.tensor(arr)
tensors2[2]=12
tensors2,arr 

(tensor([ 3,  4, 12,  6], dtype=torch.int32), array([ 3,  4, 10,  6]))

# in built functions in pytorch

In [8]:
# zeros 
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [9]:
torch.ones(3,4,dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

# Arithmetic operations

In [10]:
a=torch.tensor([3,4,5],dtype=torch.float32)
b=torch.tensor([5,6,7],dtype=torch.float64)
print(a+b)

tensor([ 8., 10., 12.], dtype=torch.float64)


In [11]:
c=torch.zeros(3)
c=torch.add(a,b,out=c)
print(c)

tensor([ 8., 10., 12.])


In [12]:
torch.add(a,b,out=c).sum() 

tensor(30.)

In [13]:
a=torch.tensor(np.arange(0,15).reshape(5,3))
b=torch.tensor(np.arange(15,30).reshape(5,3))

In [14]:
c=a+b 
c.sum()

tensor(435)

In [15]:
c[3,[0,2]]

tensor([33, 37], dtype=torch.int32)

# dot product and multi operation

In [16]:
x=torch.tensor([3,4,5,6],dtype=torch.float32)
y=torch.tensor([7,8,9,10],dtype=torch.float32)
x.mul(y)

tensor([21., 32., 45., 60.])

In [17]:
#3*7+4*8+5*9+6*10
x.dot(y)

tensor(158.)

In [18]:
# matrix multiplocation 
x=torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float64)
y=torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float64)

In [19]:
x.matmul(y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [20]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [21]:
x@y 

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

# to device

In [22]:
# check if gpu is available 
torch.cuda.is_available()

True

In [23]:
device=torch.device("cuda:0"  if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [24]:
x=torch.tensor([1,2,3,4])
x.device

device(type='cpu')

In [25]:
# move tensors to GPU 
x=x.to(device=0)
x.device

device(type='cuda', index=0)

In [26]:
y=torch.tensor([1,2,3,4],device=device)
y.device

device(type='cuda', index=0)

# in place memory operation GPU

In [27]:
t1=torch.randn(10000,10000,device="cpu")

# move tensor to gpu 
t1=t1.to(device)
print(t1.device)

# id() function to get memory address of tensor
print(f"initial memory location of t1 {id(t1)}")
x=t1 
print(f"initial memory location of x {id(x)}")

torch.cuda.synchronize()

# initial memory allocated
start_memory=torch.cuda.memory_allocated()

# inplace operation 
t1+=0.1 
t1.add_(0.1)

# inplace operation therefore the same 
print(x==t1)

print(f"final memory location of tensor t1 is :{id(t1)}")
print(f"final memory location of tensor x is :{id(x)}")

# total memory allocated after function call 
end_memory=torch.cuda.memory_allocated()

# memory allocated because of function call 
memory_allocated=end_memory=start_memory 
print(memory_allocated/1024**2)

cuda:0
initial memory location of t1 2460147625712
initial memory location of x 2460147625712
tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]], device='cuda:0')
final memory location of tensor t1 is :2460147625712
final memory location of tensor x is :2460147625712
382.00048828125


# memory out of place operation

In [28]:
# create tensor
t2 = torch.randn(10000, 10000, device="cpu")

# move tensor to gpu
t2 = t2.to(device)
print(t2.device)

# we can use id() function to get memory location of tensor
print(f"initial memory location of tensor t2 {id(t2)}")

y = t2
print(f"final memory location of y is : {id(y)}")

# Waits for everything to finish running
torch.cuda.synchronize()

# initial memory allocated
start_memory = torch.cuda.memory_allocated()

# out-place opertaions
t2 = t2 + 0.1

# since the operation was not inplace when we update t2 it will not update y
print(y == t2)

# we can use id() function to get memory location of tensor
print(f"final memory location of tensor t2 {id(t2)}")
print(f"final memory location of y is : {id(y)}")

# totall memory allocated after function call
end_memory = torch.cuda.memory_allocated()

# memory allocated because of function call
memory_allocated = end_memory - start_memory
print(memory_allocated / 1024**2)

cuda:0
initial memory location of tensor t2 2460147662576
final memory location of y is : 2460147662576
tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]], device='cuda:0')
final memory location of tensor t2 2459175237488
final memory location of y is : 2460147662576
382.0


# linear algebra
- dot product 

In [30]:
x=torch.tensor([0,1,1,1])
y=torch.tensor([0,1,1,0])
torch.dot(x,y)

tensor(2)

In [31]:
torch.sum(x*y)

tensor(2)

In [38]:
import time 
n=1000000
a=torch.arange(n)
b=torch.arange(n)

def pytorch_dot(x,y):
    return x.dot(y)

In [39]:
%timeit pytorch_dot(a,b)

567 µs ± 16.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [41]:
a1=a.tolist()
b1=b.tolist()
def plain_python(x,y):
    output=0
    for i,j in zip(x,y):
        output+=i*j 
    return output 

In [42]:
%timeit plain_python(a,b)

6.62 s ± 42.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# matrices operations

In [49]:
A=torch.arange(0,25).reshape(5,5)
A 
B=A.clone()
print(id(A),id(B))

2460147998864 2461821726528


In [50]:
A+B 

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]])

In [51]:
A-B

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [52]:
# multiplying matrices with scalars 
a=2
print(a+A)
print() 
print(a*A)

tensor([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26]])

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]])


In [53]:
# transpose a matrix 
A.T

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])

In [54]:
# hadamard product 
A*B 

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361],
        [400, 441, 484, 529, 576]])

In [59]:
# matrix multiplication 
A=torch.arange(0,10,dtype=float).reshape(2,5)
B=torch.ones(5,2,dtype=float)
torch.mm(A,B)

tensor([[10., 10.],
        [35., 35.]], dtype=torch.float64)

# prediction on multiple training example via matrix multiplication 

In [62]:
bias = torch.tensor([0.])
theta=torch.tensor([0.2,9.3])
theta=theta.view(-1,1)
x=torch.tensor([
    [1.8,9.2],
    [0.2,3.3],
    [5.2,3.4],
    [3.4,4.5],
    [6.1,7.1]
])
print(x.shape,theta.shape,bias.shape)

torch.Size([5, 2]) torch.Size([2, 1]) torch.Size([1])


In [63]:
prediction=x.matmul(theta)+bias 
prediction

tensor([[85.9200],
        [30.7300],
        [32.6600],
        [42.5300],
        [67.2500]])

# broadcasting
- broadcasting describes how tensor has to be treated during arithematic operation. 
- if we have tensors of different sizes we can broadcast the smaller array across the larger one so that they can have compatible shapes 

In [68]:
t=torch.tensor([1,-2,4])


In [69]:
t2=torch.tensor([[12,16,14],[13,17,13],[14,18,12]])
t2*2 

tensor([[24, 32, 28],
        [26, 34, 26],
        [28, 36, 24]])

# broadcasting a vector matrix

In [72]:
t2 = torch.tensor([[12, 16, 14], [13, 17, 13], [14, 18, 12]])
t1 = torch.tensor([1, 2, 3])
t1+t2

tensor([[13, 18, 17],
        [14, 19, 16],
        [15, 20, 15]])

In [76]:
t1.storage()

 1
 2
 3
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 3]

In [77]:
t1_mod=t1.expand_as(t2)
t1_mod

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [78]:
t1_mod.storage()

 1
 2
 3
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 3]

In [80]:
print(t1_mod+t2)
print(t1+t2)

tensor([[13, 18, 17],
        [14, 19, 16],
        [15, 20, 15]])
tensor([[13, 18, 17],
        [14, 19, 16],
        [15, 20, 15]])


In [84]:
t1 = torch.empty(5, 8, 10, 1)
t2 = torch.empty(  8, 1, 1,)
(t1+t2).size()

torch.Size([5, 8, 10, 1])

In [95]:
# Example where broadcasting is not possible
t1 = torch.empty(7, 8, 10, 1)
t2 = torch.empty  ( 8, 5, 1)
(t1 + t2).size()

RuntimeError: The size of tensor a (10) must match the size of tensor b (5) at non-singleton dimension 2